package com.ssi.ms.fraudreview.constant;

public class FraudReviewEnumConstant {
	public enum CertifiedClaims {
		ALL, INITIAL, ADDITIONAL, REOPENED;
	}

	public enum PersonalInfoChanges {
		NAME, EMAIL, ADDRESS, PHONENO, GENDER, ETHNICITY, RACE, EDUCATION, DISABILITY, CITIZENSHIP;
	}

	public enum PaymentPreference {
		PAYMENT, CORRESPONDENCE, TAXWITHHOLDING, ANY;
	}

	public enum Spidering {
		EVT2_SUSPEARNINGS, EVT3_SUSPWORKSEARCH, EVT4_SUSPNEWWORKSEARCH, EVT5_FAILEDIDPROOFING, EVT6_BPC_RTWAUTOCLEARED,
		EVT7_DECSDORUSEDBLOCKEDIPADDR, EVT8_CLMTUSESBLKDMRKR, EVT9_CCFILEDTOOFAST, EVT10_NEEDED, EVT11_CLMTUSESHIGHRISKMRKR,
		EVT12_CLMTUSESEMPCNTCTINFO, EVT13_BPCMULTICLMTAUTOCLEARED, DATAP1_UNRPTDBUSOWNERSHIP, DATAP2_MULSEPSFROMNEWEMPLR,
		DATAP3_MULSEPSFROMTERMEMPLR, DATAP4_MANYSIMILARCLMSATONETIME;
	}

	public enum AutoCreatedSpideringIssues {
		EVT7_SSN, EVT7_DECEASED, EVT7_IPADDRESS, EVT8_BANKINFO, EVT8_CMTEMAIL, EVT8_CMTMAILINGADDR, EVT8_CMTRESADDR, EVT8_CMTPHONENO,
		EVT8_DOB, EVT8_EMPLOYER, EVT8_EMPLOYERADDR, EVT8_EMPLOYERPHONENO, EVT8_CMTLICENSE, EVT9_TOOFAST;
	}

	public enum StateMismatch {
		RESVSLICENSE, RESVSBANK, RESVSMAIL;
	}

	public enum EmploymentMismatch {
		OVERLAPPINGFTE, DISPARATEOCCUP;
	}

	public enum LookupExcludeItems {
		QUARTERCHANGECLAIMS, CURRENTIDTHEFTITEMS, AUTOBLOCKEDITEMS, TRANSITIONALCLAIMS, DEACTIVATEDCLAIMANTS, ITEMSBEINGWORKEDON;
	}

	public enum DisplayTemplate {
		BASECLAIMANT, BASEEMPLOYMENT
	}

	public enum Extension {
		CONTACTDETAILS, IDCARD, BANKDETAILS, DEMOGRAPHICS, SPIDERINGDETAILS, CHANGEDETAILS, //Claimant Extensions
		WORKLOCATION, OTHERWORKDETAILS, UIACCOUNTNOORFEIN;  //Employment Extensions
	}
}