package com.ssi.ms.resea.database.dao;
// Generated Apr 3, 2018 10:01:16 AM by Hibernate Tools 4.0.0

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;


/**
 * ClmLofClf generated by hbm2java
 */
@Entity
@Table(name = "CLM_LOF_CLF")
@Data
public class ClmLofClfDao implements Serializable {

	@Id
	@Column(name = "CLF_ID")
	private Long clfId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_LOF_ID", nullable = false)
	private LocalOfficeLofDAO localOfficeLofDAO;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_CLM_ID")
	private ClaimClmDAO claimClmDAO;

	@Column(name = "CLF_ASSIGNED_TS")
	private Date clfAssignedTs;

	@Column(name = "CLF_ACTIVE_IND")
	private String clfActiveInd;


}
