package com.ssi.ms.resea.database.dao;

// Generated Apr 21, 2016 11:25:27 AM by Hibernate Tools 3.4.0.CR1

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.*;

/**
 * CmtNotesCnoDao generated by hbm2java
 */

@Entity
@Table(name = "CMT_NOTES_CNO")
@Data
public class CmtNotesCnoDao implements Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CNO_ID_SEQ_GEN")
	@SequenceGenerator(name = "CNO_ID_SEQ_GEN", sequenceName = "CNO_ID_SEQ", allocationSize = 1)
	@Column(name = "CNO_ID", unique = true, nullable = false, length = 15)
	private Long cnoId;

	@Temporal(TemporalType.DATE)
	@Column(name = "CNO_ENTERED_TS")
	private Date cnoEnteredTs;

	@Column(name = "CNO_ENTERED_BY", length = 10)
	private String cnoEnteredBy;

	@Column(name = "CNO_SUBJECT_TXT", length = 75)
	private String cnoSubjectTxt;

	@Column(name = "FK_CMT_ID")
	private Long fkCmtId;

	@Column(name = "CNO_LAST_UPD_BY")
	private String cnoLastUpdBy;

	@Temporal(TemporalType.DATE)
	@Column(name = "CNO_LAST_UPD_TS")
	private Date cnoLastUpdTs;

	@Column(name = "CNO_NOTES_TXT", length = 750)
	private String cnoNotesTxt;

	@Column(name = "CNO_COR_STATUS_CD", length = 4)
	private Long cnoCorStatusCd;

	@Column(name = "CNO_NOTES_TXT1", length = 750)
    private String cnoNotesTxt1;

	@Column(name = "CNO_NOTES_TXT2", length = 750)
	private String cnoNotesTxt2;

	@Column(name = "CNO_NOTES_TXT3", length = 750)
	private String cnoNotesTxt3;

	@Column(name = "CNO_NOTES_TXT4", length = 750)
	private String cnoNotesTxt4;

	@Column(name = "CNO_NOTES_TXT5", length = 750)
	private String cnoNotesTxt5;

	@Column(name = "CNO_NOTES_TXT6", length = 750)
	private String cnoNotesTxt6;

	@Column(name = "CNO_NOTES_TXT7", length = 750)
	private String cnoNotesTxt7;

	@Column(name = "CNO_NOTES_TXT8", length = 750)
	private String cnoNotesTxt8;

	@Column(name = "CNO_NOTES_TXT9", length = 750)
	private String cnoNotesTxt9;

	@Column(name = "CNO_NOTES_TXT10", length = 750)
	private String cnoNotesTxt10;

	@Column(name = "CNO_NOTES_TXT11", length = 750)
	private String cnoNotesTxt11;

	@Column(name = "CNO_NOTES_TXT12", length = 750)
	private String cnoNotesTxt12;

	@Column(name = "CNO_NOTES_TXT13", length = 750)
	private String cnoNotesTxt13;

	@Column(name = "CNO_NOTES_TXT14", length = 750)
	private String cnoNotesTxt14;

	@Column(name = "CNO_NOTES_TXT15", length = 750)
	private String cnoNotesTxt15;

	@Column(name = "CNO_NOTES_TXT16", length = 750)
	private String cnoNotesTxt16;

	@Column(name = "CNO_NOTES_TXT17", length = 750)
	private String cnoNotesTxt17;

	@Column(name = "CNO_NOTES_TXT18", length = 750)
	private String cnoNotesTxt18;

	@Column(name = "CNO_NOTES_TXT19", length = 750)
	private String cnoNotesTxt19;

}
